[package]
name = "chitchat-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.22"
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["ttf"] }
tokio = { version = "1.47.0", features = ["full"] }
